### ISSUE TITLE
TEAL error: Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by JeanetteCKittel** [hartwigmedical/hmftools#531] opened 2024-03-01 18:53 UTC
Hello, 
I'm currently encountering a problem while working with TEAL. The version I'm using is TEAL v1.2.1, cobalt_v1.15.1
purple_v3.9, GRCh38.d1.vd1.fa, picard_v3.1.1.  Below are my commands and the error I am getting.

java -Xmx30G -cp teal_v1.2.1.jar com.hartwig.hmftools.teal.TealApplication \
   -reference reference_id -reference_bam /directory/reference.bam \
   -tumor tumor_id -tumor_bam /directory/tumor.bam \
   -purple /directory/purple_res/ \
   -cobalt /directory/cobalt_res/ \
   -reference_wgs_metrics /directory/picard/reference_picard_output.txt \
   -tumor_wgs_metrics /directory/picard/tumour_picard_output.txt \
   -output_dir /directory/TEAL/output/ \
   -ref_genome_version V38 \
   -threads 7

```
18:36:58.570 INFO  [worker-3] - processed region(HPV163:0-7,233) read count(0)
18:36:58.570 INFO  [worker-0] - processed region(HPV162:0-7,214) read count(1)
18:36:58.571 INFO  [worker-3] - processed region(HPV164:0-7,233) read count(0)
18:36:58.572 INFO  [worker-0] - processed region(HPV165:0-7,129) read count(0)
18:36:58.572 INFO  [worker-3] - processed region(HPV166:0-7,212) read count(2)
18:36:58.574 INFO  [worker-3] - processed region(HPV168:0-7,204) read count(0)
18:36:58.574 INFO  [worker-3] - processed region(HPV169:0-7,252) read count(1)
18:36:58.574 INFO  [worker-0] - processed region(HPV167:0-7,228) read count(0)
18:36:58.575 INFO  [worker-3] - processed region(HPV170:0-7,417) read count(0)
18:36:58.577 INFO  [worker-0] - processed region(HPV171:0-7,261) read count(0)
18:36:58.577 INFO  [worker-3] - processed region(HPV172:0-7,203) read count(0)
18:36:58.578 INFO  [worker-3] - processed region(HPV174:0-7,359) read count(0)
18:36:58.578 INFO  [worker-0] - processed region(HPV173:0-7,297) read count(0)
18:36:58.579 INFO  [worker-3] - processed region(HPV175:0-7,226) read count(0)
18:36:58.580 INFO  [worker-3] - processed region(HPV179:0-7,228) read count(0)
18:36:58.580 INFO  [worker-0] - processed region(HPV178:0-7,314) read count(0)
18:36:58.580 INFO  [worker-3] - processed region(HPV180:0-7,356) read count(0)
18:36:58.582 INFO  [worker-3] - processed region(HPV197:0-7,278) read count(0)
18:36:58.582 INFO  [worker-3] - processed region(HPV199:0-7,184) read count(0)
18:36:58.583 INFO  [worker-0] - processed region(HPV184:0-7,324) read count(0)
18:36:58.583 INFO  [worker-3] - processed region(HPV-mCG2:0-7,152) read count(0)
18:36:58.584 INFO  [worker-3] - processed region(HPV-mCH2:0-7,190) read count(0)
18:36:58.585 INFO  [worker-0] - processed region(HPV-mCG3:0-7,095) read count(2)
18:36:58.585 INFO  [worker-3] - processed region(HPV-mFD1:0-7,286) read count(0)
18:36:58.587 INFO  [worker-3] - processed region(HPV-mFS1:0-7,167) read count(0)
18:36:58.587 INFO  [worker-0] - processed region(HPV-mFD2:0-7,219) read count(0)
18:36:58.587 INFO  [worker-3] - processed region(HPV-mFi864:0-7,247) read count(0)
18:36:58.589 INFO  [worker-3] - processed region(HPV-mKN1:0-7,300) read count(0)
18:36:58.589 INFO  [worker-0] - processed region(HPV-mKC5:0-7,143) read count(0)
18:36:58.589 INFO  [worker-3] - processed region(HPV-mKN2:0-7,299) read count(0)
18:36:58.590 INFO  [worker-5] - processed region(HPV148:0-7,164) read count(0)
18:36:58.591 INFO  [worker-3] - processed region(HPV-mL55:0-7,177) read count(0)
18:36:58.591 INFO  [worker-0] - processed region(HPV-mKN3:0-7,251) read count(0)
18:36:58.592 INFO  [worker-5] - processed region(HPV-mRTRX7:0-7,731) read count(0)
18:36:58.593 INFO  [worker-3] - processed region(HPV-mSD2:0-7,300) read count(0)
18:36:59.294 INFO  [worker-2] - processed region(chrUn_JTFH01001929v1_decoy:0-2,349) read count(0)
18:37:08.792 INFO  [worker-4] - processed region(chrUn_KN707896v1_decoy:0-33,125) read count(8)
18:37:27.619 INFO  [worker-1] - processed region(chrX:0-99,999,999) read count(3071)
18:37:27.620 INFO  [main] - 2795 bam reader tasks finished
18:37:27.620 INFO  [main] - writer thread finished
18:37:27.620 INFO  [main] - initial BAM file processing complete
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
        at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
        at java.base/java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:413)
        at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.base/java.util.Arrays.sort(Arrays.java:1108)
        at java.base/java.util.Arrays.sort(Arrays.java:1302)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
        at java.base/java.util.Collections.sort(Collections.java:145)
        at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sort(MutableCollectionsJVM.kt:31)
        at com.hartwig.hmftools.teal.telbam.BamProcessor.getMissingReadRegions(BamProcessor.kt:200)
        at com.hartwig.hmftools.teal.telbam.BamProcessor.processBam(BamProcessor.kt:79)
        at com.hartwig.hmftools.teal.telbam.TelbamApp.processBam(TelbamApp.kt:69)
        at com.hartwig.hmftools.teal.TealApplication$StandaloneMode.run(TealApplication.kt:66)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:191)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)
``` 

Thanks!

**Comment by hongwingl** [comment] 2024-03-01 23:16
This is a duplicate of #518, the bug been fixed in teal 1.2.2

**Closed by hongwingl** 2024-03-01 23:16 UTC
