### ISSUE TITLE
Adjacent Genes Have Same minCopyNumber and maxCopyNumber

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#277] opened 2022-04-19 04:00 UTC
I wouldn't expect this.

```
$ grep -e chromosome -e CDY2A -e KDM5D -e PRORY -e DAZ1 -e CDY1$'\t' CSCC_0022-P1.purple.cnv.gene.tsv | cut -f 1-6
chromosome      start   end     gene    minCopyNumber   maxCopyNumber
chrY    18025789        18028597        CDY2A   0.1401  5.1765
chrY    19705415        19744923        KDM5D   0.1401  5.1765
chrY    21382954        21386360        PRORY   0.1401  5.1765
chrY    23129355        23199094        DAZ1    0.1401  5.1765
chrY    25622162        25624902        CDY1    0.1401  5.1765
```

Note that gene coordinates do not overlap. I only found this for one sample out of 49.

**Comment by p-priestley** [comment] 2022-04-19 04:26
That is indeed odd.   I am thinking it might be something strange to do with chrY  Do you have the somatic.cnv output for chr Y for this sample?

**Comment by DarioS** [comment] 2022-04-19 05:00
Yes.

```
$ tail /verona/nobackup/dario/HeadNeck/cSCC/purityPloidy/CSCC_0022-P1.purple.cnv.somatic.tsv 
chr21   32968001        33555000        3.0601  160     0.5934  0.6651  NONE    NONE    BAF_WEIGHTED    566     0.4503  32968001        32968001        1.0250  2.0352
chr21   33555001        39908000        2.0363  1323    0.5457  0.5089  NONE    NONE    BAF_WEIGHTED    6031    0.4299  33555001        33555001        0.9999  1.0363
chr21   39908001        46709983        2.9978  1743    0.5956  0.6704  NONE    TELOMERE        BAF_WEIGHTED    5342    0.4842  39908001        39908001        0.9882  2.0097
chr22   1       14004552        4.7678  0       0.0000  0.7913  TELOMERE        CENTROMERE      BAF_WEIGHTED    5       0.2384  1       1       0.9950  3.7728
chr22   14004553        40981000        2.9973  5003    0.5941  0.6680  CENTROMERE      NONE    BAF_WEIGHTED    20182   0.4714  14004553        14004553        0.9950  2.0023
chr22   40981001        50818468        1.9999  2118    0.5495  0.5085  NONE    TELOMERE        BAF_WEIGHTED    8423    0.5040  40981001        40981001        0.9830  1.0168
chrX    1       60509060        1.0088  0       0.0000  1.0000  TELOMERE        CENTROMERE      BAF_WEIGHTED    50078   0.3978  1       1       0.0000  1.0088
chrX    60509061        156040895       1.9774  0       0.0000  1.0000  CENTROMERE      TELOMERE        BAF_WEIGHTED    78523   0.3875  60509061        60509061        0.0000  1.9774
chrY    1       10430491        5.1765  0       0.0000  1.0000  TELOMERE        CENTROMERE      LONG_ARM        460     0.4065  1       1       0.0000  5.1765
chrY    10430492        57227415        5.1765  0       0.0000  1.0000  CENTROMERE      TELOMERE        BAF_WEIGHTED    134     0.3906  10430492        10430492        0.0000  5.1765
```

**Comment by p-priestley** [comment] 2022-04-19 05:09
Thanks.   Do you mind also showing the rest of the columns of the CSCC_0022-P1.purple.cnv.gene.tsv for those 5 genes please?

**Comment by p-priestley** [comment] 2022-04-19 05:09
I think what is happening is that it has tried to inferred a germline deletion in these genes

**Comment by DarioS** [comment] 2022-04-19 05:15
I show the full set of columns.

```
chromosome      start   end     gene    minCopyNumber   maxCopyNumber   unused  somaticRegions  germlineHomDeletionRegions      germlineHetToHomDeletionRegions transcriptId    transcriptVersion       chromosomeBand  minRegions      minRegionStart  minRegionEnd    minRegionStartSupport   minRegionEndSupport     minRegionMethod minMinorAllelePloidy
chrY    18025789        18028597        CDY2A   0.1401  5.1765  0       1       0       1       ENST00000426790 1       q11.222 1       15875001        26638000        NONE    UNKNOWN GERMLINE_HET2HOM_DELETION       0.0000
chrY    19705415        19744923        KDM5D   0.1401  5.1765  0       1       0       1       ENST00000317961 8       q11.223 1       15875001        26638000        NONE    UNKNOWN GERMLINE_HET2HOM_DELETION       0.0000
chrY    21382954        21386360        PRORY   0.1401  5.1765  0       1       0       1       ENST00000382764 1       q11.223 1       15875001        26638000        NONE    UNKNOWN GERMLINE_HET2HOM_DELETION       0.0000
chrY    23129355        23199094        DAZ1    0.1401  5.1765  0       1       0       1       ENST00000405239 5       q11.223 1       15875001        26638000        NONE    UNKNOWN GERMLINE_HET2HOM_DELETION       0.0000
chrY    25622162        25624902        CDY1    0.1401  5.1765  0       1       0       1       ENST00000306609 4       q11.23  1       15875001        26638000        NONE    UNKNOWN GERMLINE_HET2HOM_DELETION       0.0000

```

**Comment by p-priestley** [comment] 2022-04-19 05:41
Ok.  The problem is that these were marked as a 'germlineHetToHomDeletionRegions=1'.   This was an early attempt by me to call germline deletions but it is quite buggy and I have not used for a long time.   We have actually removed this in v3.2 and replaced with 'germline_deletion' logic which writes a separate file for germline deletions detected that affect genes.

One way to avoid in the meantime is to ignore deletions in 
genes with germlineHetToHomDeletionRegions or germlineHomDeletions > 0

**Comment by p-priestley** [comment] 2022-04-19 05:42
We actually did that in our reporting for a while.    Sorry that this is messy, but neater in the latest version

**Closed by p-priestley** 2022-04-19 05:42 UTC
