### ISSUE TITLE
SAGE not outputting any variants

### ISSUE THREAD

**Issue by LukeGoodsell** [hartwigmedical/hmftools#58] opened 2019-10-08 11:28 UTC
I'm using SAGE v1.1 but it doesn't seem to output any variants for me. I'm using a human tumour-normal dataset in which I have some somatic SNV, MNV and indel calls that are pretty convincing (called by multiple callers and quite clear when manually viewed in IGV), so I would expect some output from SAGE. Please can you tell me what I'm doing wrong?

I have downloaded and gunzipped the CodingRegions.bed file from [here](https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMFTools-Resources%2FSage).

I'm using candidate calls from Strelka like this:

```
zcat "strelka_snvs.vcf.gz" \
    | awk 'BEGIN { FS = OFS = "\t" }
        !/^#/ { print $1, $2, $4, $5 }' \
    > candidates.tsv
```
I have approximately 450,000 candidate events.

Then using SAGE like this:

```
java -Xmx8G -Xms4G -jar sage.jar \
        -tumor "[TUMOUR_ID]" \
        -tumor_bam "[TUMOUR_ID].bam" \
        -reference "[NORMAL_ID]" \
        -reference_bam "[NORMAL_ID].bam" \
        -known_hotspots "candidates.tsv" \
        -coding_regions "CodingRegions.bed" \
        -ref_genome "[REF_GENOME_FASTA_FILE]" \
        -out "[TUMOUR_ID].vcf.gz";
```

All I get from SAGE, though, is this:

```
##fileformat=VCFv4.2
##FILTER=<ID=GERMLINE_INDEL,Description="Set if indel has any germline indels at that site">
##FILTER=<ID=LOW_CONFIDENCE,Description="Set if excessive germline reads or insufficient quality or tumor reads">
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allelic Frequency">
##INFO=<ID=GHBL,Number=1,Type=Float,Description="Germline Heterozygous Binomial Likelihood. Only applies when germline
##INFO=<ID=HOTSPOT,Number=1,Type=String,Description="Hotspot Type: known, inframe">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  [NORMAL]  [TUMOUR]
```

**Comment by p-priestley** [comment] 2019-10-08 11:47
This current version of SAGE is highly sensitive and designed for hotspot calling only where there is a high prior likelihood of a somatic variant.     It is designed to supplement a whole genome caller to make sure we don't miss known pathogenic variants.   Specifically it tests for the exact variants in the known_hotspots file (curated from CIVIC, OncoKb and CGI)  and for any inframe indel within the coding_regions specified (since we find that inframe indels in known oncogenes are nearly always drivers)

An empty vcf indicates no support for any known hotspots or inframe indels are found in this sample.   Please let us know if you find an example otherwise and I would be happy to take a look.

We will release a new version of SAGE shortly that will support full genome calling.

**Comment by LukeGoodsell** [comment] 2019-10-08 12:20
Thanks for such a quick reply, @p-priestley.

Instead of using the pre-generated `KnownHotspots.tsv` file you describe, I'm generating one using the output from Strelka for the same sample. I'm doing this because I'd like to see how SAGE annotates the calls, and whether it can provide useful filtering signal for my data.

However, none of the calls seem to make it through at all. Could this be because my BAM and reference FASTA file use the `chr` prefix for chromosome names? I've tried adding the `chr` prefix to the input `known_hotspots` and `coding_regions` files, but that causes a NullPointerException when it tries to get the sequence length:

```
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.hotspot.VariantHotspotEvidenceFactory.lambda$evidence$1(VariantHotspotEvidenceFactory.java:75)
```

[VariantHotspotEvidenceFactory.java:75](https://github.com/hartwigmedical/hmftools/blob/sage%E2%80%94v1.1/hmf-common/src/main/java/com/hartwig/hmftools/common/hotspot/VariantHotspotEvidenceFactory.java#L75)

Does SAGE require all input files to not have a `chr` prefix?

**Comment by p-priestley** [comment] 2019-10-08 12:31
sorry.  misintepreted your first comment, but I get now what you are doing.

Could you please provide a few lines of the candidates.tsv file and also the ref genome version you are using to help diagnose the issue.

**Comment by LukeGoodsell** [comment] 2019-10-08 13:03
No problem.

Top of the `candidates.tsv` file:

```
$ head candidates.tsv
1       10120   T       C
1       10427   A       C
1       10469   C       G
1       13896   C       A
1       15688   C       T
1       16731   C       G
1       16856   A       G
1       17379   G       A
1       20304   G       C
1       61987   A       G
```

Here it is with control characters visible showing tabs and line endings:

```
$ head candidates.tsv | cat -A
1^I10120^IT^IC$
1^I10427^IA^IC$
1^I10469^IC^IG$
1^I13896^IC^IA$
1^I15688^IC^IT$
1^I16731^IC^IG$
1^I16856^IA^IG$
1^I17379^IG^IA$
1^I20304^IG^IC$
1^I61987^IA^IG$
```

I'm using UCSC hg19, taken from `ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg19/ucsc.hg19.fasta.gz` and uncompressed. The same file was used for aligning the reads. It has a 'chr' prefix for contigs, as do my BAMs.

**Comment by jonbaber** [comment] 2019-10-09 00:44
Hi Luke, 

This is an internal tool so we have never added support for "chr" style contigs. Having said that, I just tried it and including "chr" in the candidates.tsv file and an empty bed file worked fine for me:

```
$ cat candidates.tsv
chr1	10462	T	C

$ java -Xmx8G -Xms4G \
-cp /data/common/tools/sage_v1.1/sage.jar com.hartwig.hmftools.sage.SageHotspotApplication \
-tumor COLO829T -tumor_bam /data/data_archive/COLO829/hg38_bams/COLO829T.sorted.bam \
-reference COLO829R -reference_bam /data/data_archive/COLO829/hg38_bams/COLO829R.sorted.bam \
-known_hotspots /data/experiments/191009_hg38_sage/candidates.tsv \
-coding_regions /data/experiments/191009_hg38_sage/empty.bed \
-ref_genome /data/common/refgenomes/Homo_sapiens.GRCh38/Homo_sapiens_assembly38.fasta \
-out /data/experiments/191009_hg38_sage/hg38sage.vcf

$ cat hg38sage.vcf
##fileformat=VCFv4.2
##FILTER=<ID=GERMLINE_INDEL,Description="Set if indel has any germline indels at that site">
##FILTER=<ID=LOW_CONFIDENCE,Description="Set if excessive germline reads or insufficient quality or tumor reads">
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allelic Frequency">
##INFO=<ID=GHBL,Number=1,Type=Float,Description="Germline Heterozygous Binomial Likelihood. Only applies when germline alt support = 1">
##INFO=<ID=HOTSPOT,Number=1,Type=String,Description="Hotspot Type: known, inframe">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	COLO829R	COLO829T
chr1	10462	.	T	C	104	PASS	AF=0.015;HOTSPOT=known	GT:AD:DP	0/1:56,0:56	0/1:189,3:197

```
Note that the bed file is empty and the bams and ref genome all use the "chr" contig style.

I know you mentioned you tried this already, but perhaps have another go with the empty bed file.

Regards, Jon

**Comment by LukeGoodsell** [comment] 2019-10-09 10:43
Thanks for your reply, @jonbaber.

I hadn't tried using an empty coding_regions BED file. When I use an empty BED file, and my TSV file has a "chr" prefix, I get the NullPointerException still:

```
10:25:45 - Loading coding regions from CodingRegions.bed
10:25:45 - Loading known hotspots from candidates.tsv
10:25:46 - Looking for potential inframe indel locations
10:25:46 - Looking for evidence of hotspots in tumor bam tumour.bam
10:27:59 - Complete
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.hotspot.VariantHotspotEvidenceFactory.lambda$evidence$1(VariantHotspotEvidenceFactory.java:75)
        at com.hartwig.hmftools.common.hotspot.SAMSlicer.slice(SAMSlicer.java:40)
        at com.hartwig.hmftools.common.hotspot.VariantHotspotEvidenceFactory.evidence(VariantHotspotEvidenceFactory.java:89)
        at com.hartwig.hmftools.sage.SageHotspotApplication.run(SageHotspotApplication.java:100)
        at com.hartwig.hmftools.sage.SageHotspotApplication.main(SageHotspotApplication.java:49)
```

If I drop the "chr" prefix from the TSV file, but still use an empty BED file, it completes without error but reports no variants.

Is a particular format required for the FASTA sequence IDs? Mine lack ancilliary annotation and look like this:

```
$ grep '>' ucsc.hg19-GATKBundle.fa | head
>chrM
>chr1
>chr2
>chr3
>chr4
>chr5
>chr6
>chr7
>chr8
>chr9
```

**Comment by jonbaber** [comment] 2019-10-09 10:52
Looks like you've found the problem!

The line causing the exception is trying to use the ref genome to get the length of the chromosome:
```
 int sequenceLength = sequenceFile.getSequenceDictionary().getSequence(hotspot.chromosome()).getSequenceLength();
```

The file I am using contains the length annotation:
```
grep '>' Homo_sapiens_assembly38.fasta | head
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
>chr2  AC:CM000664.2  gi:568336022  LN:242193529  rl:Chromosome  M5:f98db672eb0993dcfdabafe2a882905c  AS:GRCh38
```

**Comment by LukeGoodsell** [comment] 2019-10-09 15:07
Sadly, no such luck. I've added the same annotations to the FASTA headers but I still get the same error - I suspect htsjdk is taking the length from the FAI anyway. If the length was null, I wouldn't expect the NullPointerException to occur when it is defined on line 75 but rather when it is used at line 77. I suspect that the Null is one of the objects against which a method is being called, such as the output of `getSequence(hotspot.chromosome())`.

**Comment by jonbaber** [comment] 2019-10-14 09:12
I am sorry I wasn't able to help you resolve your problem. As this is an internal application that we are currently trying to phase out and I am unable to reproduce the problem I am going to close this issue.

**Closed by jonbaber** 2019-10-14 09:12 UTC
