### ISSUE TITLE
Linx plotting error

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#514] opened 2024-02-06 08:32 UTC
Hi, 
I'm running Linx (v1.24.1, through Oncoanalyser) and for some samples I get a plotting error. 
The SvVisualiser command is:
```
java \
    -Xmx16g \
    -cp /opt/linx/linx.jar \
    com.hartwig.hmftools.linx.visualiser.SvVisualiser \
    -sample ACH-000012 \
    -vis_file_dir linx_somatic \
    -ref_genome_version 38 \
    -ensembl_data_dir ensembl_data \
    -circos /opt/conda/bin/circos \
    -threads 4 \
    -plot_out plots/all/ \
    -data_out reportable/all_data/
```
This will plot some clusters properly until reaching cluster-39:
```
10:02:10 - [INFO ] - Generating ACH-000012.cluster-39.sv2.003.png via command: /opt/conda/bin/circos -nosvg -conf /nfs/research/icortes/DATA/broad.wgs/oncoanalyser/work/7f/c7976a321bce556e06e290072d6e8a/data/all_data/ACH-000012.cluster-39.sv2.circos.003.conf -outputdir /nfs/research/icortes/DATA/broad.wgs/oncoanalyser/work/7f/c7976a321bce556e06e290072d6e8a/plots/all -outputfile ACH-000012.cluster-39.sv2.003.png
10:02:13 - [INFO ] - Executing R script via command: Rscript /tmp/script14616716124940271539.R data/all_data//ACH-000012.cluster-39.sv2.chromosome.circos data/all_data//ACH-000012.cluster-39.sv2.cytoBand.txt plots/all//ACH-000012.cluster-39.sv2.003.png 48.0 150 6
10:02:33 - [FATAL] - Error executing R script. Examine error file /tmp/chromosomeRangePlot.R3869294969340833157.error for details.
10:02:33 - [WARN ] - error adding chromosomal context
java.util.concurrent.ExecutionException: java.lang.Exception: plotting error
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.run(SvVisualiser.java:131)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.main(SvVisualiser.java:374)
Caused by: java.lang.Exception: plotting error
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.createImageFrame(SvVisualiser.java:354)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.lambda$submitFrame$29(SvVisualiser.java:323)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I can confirm that data/all_data//ACH-000012.cluster-39.sv2.chromosome.circos is empty, which prompts the R error:
```
Error in read.table(chromosomeRangePath, h = F, sep = "\t", comment = "!",  : 
  no lines available in input
Execution halted
```
I am not sure as to where to start debugging this one, so any help is appreciated. 

Thanks!

**Comment by charlesshale** [comment] 2024-02-15 23:40
Would it be possible for you to share the Linx VIS files so I can debug this? If so, email me directly: c.shale@hartwigmedicalfoundation.nl

Alternatively you could try running the latest Linx release to see the issue has already been addressed:
https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.25

**Comment by jaesvi** [comment] 2024-02-16 11:52
Sent via email. I can also confirm that error remains in linx-v1.25

**Comment by charlesshale** [comment] 2024-02-27 19:42
The cause of this is:
- the sample has SVs on chrY but Purple determines the gender/sex as female
- no Purple copy number records are written for chrY
- when Linx attempts to generate a plot for a pair of clustered SGLs on chrY it fails to find copy number data and the R-script throws an error

This has been addressed in Purple as per this minor release:
https://github.com/hartwigmedical/hmftools/releases/tag/purple-v4.0.2

**Closed by charlesshale** 2024-02-27 19:42 UTC

**Comment by p-levy** [comment] 2025-02-17 10:41
Hi @charlesshale, 
Not sure if I'm supposed to re-open this issue or open a new one. I'm getting a similar error and I do find SVs reported on chrY but the reported sex is Male. I'm running oncoanalyser v6.0 in targeted mode (WES panel). This happened only for one patient while the pipeline ran successfully for 7 others. 

The command/error: 
```
Command executed:

  # NOTE(SW): the output plot directories are always required for ORANGE, which is straightfoward to handle with POSIX
  # fs but more involved with FusionFS since it will not write empty directories to S3. A placeholder file can't be
  # used in the plot directory to force FusionFS to create the directory as ORANGE will treat the placeholder as a PNG
  # and fail. Optional outputs are possible but requires further channel logic and output to detect when complete.
  # Instead I place the two plot output directories under a parent directory, only operating on that to allow use of a
  # placeholder and support empty outputs when using FusionFS. Handling missing/non-existent directories are deferred
  # to downstream processes, bypassing the need to implement further channel operations.
  
  mkdir -p plots/
  
  # NOTE(SW): LINX v1.24.1 require trailing slashes for the -plot_out and -data_out arguments since no filesystem
  # separator is used when constructing fusion plot output filepaths.
  
  # https://github.com/hartwigmedical/hmftools/blob/linx-v1.24.1/linx/src/main/java/com/hartwig/hmftools/linx/visualiser/circos/ChromosomeRangeExecution.java#L22-L29
  # https://github.com/hartwigmedical/hmftools/blob/linx-v1.24.1/linx/src/main/java/com/hartwig/hmftools/linx/visualiser/circos/FusionExecution.java#L18-L23
  
  # Generate all chromosome and cluster plots by default
  
  linx \
      -Xmx36721970381 \
      com.hartwig.hmftools.linx.visualiser.SvVisualiser \
       \
      -sample GOIGROS004CFDNA \
      -vis_file_dir linx_somatic \
      -ref_genome_version 38 \
      -ensembl_data_dir ensembl_data \
      -circos $(which circos) \
      -threads 6 \
      -plot_out plots/all/ \
      -data_out data/all/
  
  # Rerun LINX to render only reportable cluster plots in a separate directory. While this is regenerating existing
  # cluster plots, the number of reportable plots is generally very small and I prefer to rely on the internal LINX
  # logic to determine whether a cluster is reportable rather than attempting to infer manually to copy out target
  # plot files.
  
  # The ORANGE report receives only reportable clusters while the gpgr LINX report receives chromosome and all cluster
  # plots.
  
  # https://github.com/hartwigmedical/hmftools/blob/linx-v1.24.1/linx/src/main/java/com/hartwig/hmftools/linx/visualiser/SampleData.java#L220-L236
  
  linx \
      -Xmx36721970381 \
      com.hartwig.hmftools.linx.visualiser.SvVisualiser \
       \
      -sample GOIGROS004CFDNA \
      -vis_file_dir linx_somatic \
      -ref_genome_version 38 \
      -ensembl_data_dir ensembl_data \
      -circos $(which circos) \
      -plot_reportable \
      -threads 6 \
      -plot_out plots/reportable/ \
      -data_out data/reportable/
  
  # Create placeholders to force FusionFS to create parent plot directory on S3
  if [[ $(ls plots/ | wc -l) -eq 0 ]]; then
      touch plots/.keep;
  fi;
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ONCOANALYSER:TARGETED:LINX_PLOTTING:VISUALISER":
      linx: $(linx -version | sed 's/^.* //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  
  The following object is masked from 'package:GenomeInfoDb':
  
      intersect
  
  The following objects are masked from 'package:IRanges':
  
      collapse, desc, intersect, setdiff, slice, union
  
  The following objects are masked from 'package:S4Vectors':
  
      first, intersect, rename, setdiff, setequal, union
  
  The following objects are masked from 'package:BiocGenerics':
  
      combine, intersect, setdiff, union
  
  The following objects are masked from 'package:stats':
  
      filter, lag
  
  The following objects are masked from 'package:base':
  
      intersect, setdiff, setequal, union
  
  Linking to ImageMagick 7.1.1.36
  Enabled features: cairo, fontconfig, freetype, fftw, heic, rsvg, webp, x11
  Disabled features: ghostscript, lcms, pango, raw
  Error in read.table(chromosomeRangePath, h = F, sep = "\t", comment = "!",  : 
    no lines available in input
  Execution halted
  16:40:59.916 [FATAL] error executing R script
  16:40:59.917 [WARN ] error adding chromosomal context
  16:40:59.961 [INFO ] generating GOIGROS004CFDNA.chr5.003.png via command: /opt/conda/bin/circos -nosvg -conf data/all/GOIGROS004CFDNA.chr5.circos.003.conf -outputdir plots/all -outputfile GOIGROS004CFDNA.chr5.003.png
  16:41:03.740 [INFO ] generating GOIGROS004CFDNA.chr6.001.png via command: /opt/conda/bin/circos -nosvg -conf data/all/GOIGROS004CFDNA.chr6.circos.001.conf -outputdir plots/all -outputfile GOIGROS004CFDNA.chr6.001.png
  16:41:04.180 [INFO ] generating GOIGROS004CFDNA.chr3.005.png via command: /opt/conda/bin/circos -nosvg -conf data/all/GOIGROS004CFDNA.chr3.circos.005.conf -outputdir plots/all -outputfile GOIGROS004CFDNA.chr3.005.png
  16:41:05.812 [INFO ] generating GOIGROS004CFDNA.chr10.000.png via command: /opt/conda/bin/circos -nosvg -conf data/all/GOIGROS004CFDNA.chr10.circos.000.conf -outputdir plots/all -outputfile GOIGROS004CFDNA.chr10.000.png
  16:41:06.222 [INFO ] generating GOIGROS004CFDNA.chr21.001.png via command: /opt/conda/bin/circos -nosvg -conf data/all/GOIGROS004CFDNA.chr21.circos.001.conf -outputdir plots/all -outputfile GOIGROS004CFDNA.chr21.001.png
  java.util.concurrent.ExecutionException: java.lang.Exception: plotting error
  	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
  	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
  	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.run(SvVisualiser.java:127)
  	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.main(SvVisualiser.java:379)
  Caused by: java.lang.Exception: plotting error
  	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.createImageFrame(SvVisualiser.java:362)
  	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.lambda$submitFrame$29(SvVisualiser.java:331)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)

Work dir:
  /mnt/petasan_immuno/.pierre/GOI/work/11/e3c546853a61d7702efd968b2af299

Container:
  /mnt/bioinfnas/immuno/plevy/proj/hmftools/singularity/singularity_images/linx\:2.0-rc.1.sif
```
Here's the linx_somatic folder. 
[linx_somatic.zip](https://github.com/user-attachments/files/18823882/linx_somatic.zip)

Let me know if you need anything else. 
Thanks!
Pierre
