### ISSUE TITLE
Large regions with no BAF points

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#55] opened 2019-10-03 09:39 UTC
Below is a sample with purity/ploidy 0.84/1.93. It passes all the QC tests. You can notice that there are no BAF points in certain large (non-'gap') regions (e.g. chrom 3, 5 and 17), but copy number is left as 2. We're chasing it a bit more from our side, but just wanted to know if you get cases like these and how is the CN determined without BAF info. Do you know what might cause no BAF points in a region?

Thanks for the awesome tools!
Cheers - Peter

![circos_baf](https://user-images.githubusercontent.com/29562861/66115963-40f4d680-e615-11e9-9ac5-91fba3c1ccc4.png)

**Comment by p-priestley** [comment] 2019-10-03 10:26
I checked all our samples and was able to find just 1 with a similar problem where it was missing information in 2 large segments.  We had not noticed this yet, but in our case at least the BAF points are missing in AMBER.    We will investigate in the morning and let you know what is the cause and how to fix.    

Note that PURPLE will handle this gracefully and the copy number for those segments will be correct.     The minor allele copy number will be inferred from surrounding segments and will also very likely be correct.

**Comment by p-priestley** [comment] 2019-10-09 04:36
Peter - we have investigated this on our internal sample with a similar observation of large segments with no BAF points.    We found that amber had infact run correctly and that the patient had large sections on multiple chromsomes with no heterozygous points.    

We think that the most likely explanation is consanguinity although we are not able to verify on our patient.     Could you please consider if this is possible for your patient?     Again, I think PURPLE will handle this gracefully and  very likely produce an accurate fit for the region,

If you find a clear heterozygous point in your bam at a location in our bed file that is not called by amber we are happy to take a further look

**Closed** 2019-10-11 05:14 UTC
