### ISSUE TITLE
Purple: error parsing recovery VCF

### ISSUE THREAD

**Issue by freerkvandijk** [hartwigmedical/hmftools#83] opened 2020-03-20 13:43 UTC
Hi,

I'm running Purple from the gridss_purple_linx pipeline for a cohort of tumor-normal samples which works fine for almost all samples. A couple of my samples crash with an error generated during Purple execution. I am running the following software versions:
gridss-purple-linx v1.2.0
gridss 2.7.3
amber 3.1
cobalt 1.8
purple 2.36
sv-linx 1.7

My Purple logs look like this:

12:10:23 - PURPLE version: 2.36
12:10:23 - Reference Sample: PMRBM000AIO.PMRBM000AIN_N, Tumor Sample: PMRBM000AIO.PMRBM000AIN_T
12:10:23 - Output Directory: .//purple
12:10:23 - No somatic vcf supplied
12:10:24 - Using ref genome: HG38
12:10:25 - Reading cobalt ratios from .//cobalt/PMRBM000AIO.PMRBM000AIN_T.cobalt.ratio.tsv
12:10:29 - Reading cobalt reference segments from .//cobalt/PMRBM000AIO.PMRBM000AIN_N.cobalt.ratio.pcf
12:10:29 - Reading cobalt tumor segments from .//cobalt/PMRBM000AIO.PMRBM000AIN_T.cobalt.ratio.pcf
12:10:29 - Reading amber bafs from .//amber/PMRBM000AIO.PMRBM000AIN_T.amber.baf.tsv
12:10:30 - Reading amber pcfs from .//amber/PMRBM000AIO.PMRBM000AIN_T.amber.baf.pcf
12:10:30 - Average amber tumor depth is 129 reads implying an ambiguous BAF of 0.538
12:10:30 - Sample gender is female
12:10:30 - Loading structural variants from ./gridss/PMRBM000AIO.PMRBM000AIN_T.gridss.somatic.vcf.gz
12:10:30 - Somatic variants support disabled.
12:10:30 - Applying segmentation
12:10:30 - Merging reference and tumor ratio break points
12:10:30 - Reading GC Profiles from /hpc/local/CentOS7/pmc_kuiper/software/gridss-purple-linx/gridss-purple-linx-v1.2.0//dbs/gc/GC_profile.hg38.1000bp.cnp
12:10:41 - Fitting purity
12:11:04 - Calculating copy number
12:11:04 - Loading recovery candidates from ./gridss/PMRBM000AIO.PMRBM000AIN_T.gridss.full.somatic.vcf.gz

The error is this:
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._Un_KI270438v1
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.valueOf(HumanChromosome.java:9)
        at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.fromString(HumanChromosome.java:66)
        at com.hartwig.hmftools.common.genome.position.GenomePosition.compareTo(GenomePosition.java:16)
        at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.toContext(RecoverStructuralVariants.java:213)
        at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.lambda$recoverFromUnexplainedSegments$2(RecoverStructuralVariants.java:183)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.recoverFromUnexplainedSegments(RecoverStructuralVariants.java:183)
        at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.recoverVariants(RecoverStructuralVariants.java:80)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.recoverStructuralVariants(PurityPloidyEstimateApplication.java:276)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:167)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:99)

I don't know if this for example is related to issue #69? Can you perhaps help me out or point me in the right direction?

Regards,

Freerk

**Comment by jonbaber** [comment] 2020-04-07 00:19
Sorry for the delayed response.

This is caused by an issue trying to recover a structural variant in an alt contig. This is fixed in PURPLE 2.41 which will be released shortly.

In the meantime, you can work around this issue by filtering any variants outside of chromosomes 1-22,X and Y in the recovery VCF.

**Closed by jonbaber** 2020-04-07 00:19 UTC
