### ISSUE TITLE
Isofox: Error in output log

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#198] opened 2021-08-13 09:26 UTC
I have run Isofox 1.2 (TRANSCRIPT_COUNTS;NOVEL_LOCATIONS;FUSIONS) against tumor bam files from STAR 2.7.9a aligned RNAseq data using the non-default parameters described in the Isofox README with HG38 (GCA_000001405.15_GRCh38_no_alt_analysis_set.fna).
For at least some of the Isofox runs, I am getting ERRORs interspersed about every 10-20k rows in the log like the following:
15:14:16 - [ERROR] - task execution error: java.lang.NumberFormatException: For input string: "chr14" stack: {}
java.lang.NumberFormatException: For input string: "chr14"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.chromosomeRank(HumanChromosome.java:121)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.lowerChromosome(HumanChromosome.java:106)
	at com.hartwig.hmftools.isofox.fusion.FusionFragmentBuilder.setFragmentProperties(FusionFragmentBuilder.java:99)
	at com.hartwig.hmftools.isofox.fusion.FusionFragment.<init>(FusionFragment.java:75)
	at com.hartwig.hmftools.isofox.fusion.FusionFinder.processReadGroups(FusionFinder.java:313)
	at com.hartwig.hmftools.isofox.fusion.FusionFinder.processInterChromosomalReadGroups(FusionFinder.java:269)
	at com.hartwig.hmftools.isofox.BamFragmentReader.assignTranscriptCounts(BamFragmentReader.java:286)
	at com.hartwig.hmftools.isofox.BamFragmentReader.call(BamFragmentReader.java:167)
	at com.hartwig.hmftools.isofox.BamFragmentReader.call(BamFragmentReader.java:48)
	at com.hartwig.hmftools.isofox.common.TaskExecutor.executeChromosomeTask(TaskExecutor.java:25)
	at com.hartwig.hmftools.isofox.Isofox.allocateBamFragments(Isofox.java:215)
	at com.hartwig.hmftools.isofox.Isofox.runAnalysis(Isofox.java:156)
	at com.hartwig.hmftools.isofox.Isofox.main(Isofox.java:499)

From the list of output files in the README, it seems that almost all expected files are created if I use a single thread, except there was only 1 fusion file and no sample_id.isf.frag_length.csv file.  If I use >1 thread, then the run crashes and does not create some of the files (especially, I was looking for the gene and transcript data files, but they were missing).  I suspect that the expected output (related to fusions?) from the process that caused the error is not complete, but I have no way to tell if they are complete or not.

**Comment by charlesshale** [comment] 2021-08-13 10:54
Hi Todd,

Isofox is failing to parse the chromosome string although the code should handle it having the 'chr' prefix or not. 

I can't see why the number of threads would impact the output files, but first we need to understand the cause of the exception above. 

Would you be able to provide a slice of the BAM file you are using and the arguments passed to Isofox? If so, email them to c.shale@hartwigmedicalfoundation.nl.

thanks,

**Comment by charlesshale** [comment] 2021-08-17 09:15
Fixed in Isofox v1.3 beta:

https://github.com/hartwigmedical/hmftools/releases/tag/isofox-v1.3_beta

**Closed by charlesshale** 2021-08-17 09:15 UTC
