### ISSUE TITLE
PURPLE error with mateID

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#62] opened 2019-11-14 10:47 UTC
Hi,
I am having an error with PURPLe (v2.34) that I cannot get a workaround. It launches when loading the recovery candidates. Below the relevant lines
`
11:38:01 - Loading recovery candidates from /hpc/cog_bioinf/cuppen/project_data/Jose_ovarian/heterogeneity/bams/MC-H1/MC-H1.2_O_HMF/structuralVariants/gridss/OC114-blood-P18-53308-B79_OC114-2-organoid-E18-00606-II-O88/OC114-2-organoid-E18-00606-II-O88.gridss.somatic.full.vcf.gz
Exception in thread "main" java.io.IOException: Unable to find mateId gridss12_25194h between 71146592 and 71146892

	at com.hartwig.hmftools.common.variant.recovery.RecoveredVariantFactory.lambda$findMate$4(RecoveredVariantFactory.java:209)

	at java.util.Optional.orElseThrow(Optional.java:290)

	at com.hartwig.hmftools.common.variant.recovery.RecoveredVariantFactory.findMate(RecoveredVariantFactory.java:209)

	at com.hartwig.hmftools.common.variant.recovery.RecoveredVariantFactory.recoverAllVariantAtIndex(RecoveredVariantFactory.java:94)

	at com.hartwig.hmftools.common.variant.recovery.RecoveredVariantFactory.recoverVariantAtIndex(RecoveredVariantFactory.java:67)

	at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.recoverFromUnbalancedVariants(RecoverStructuralVariants.java:128)

	at com.hartwig.hmftools.common.variant.recovery.RecoverStructuralVariants.recoverVariants(RecoverStructuralVariants.java:81)

	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.recoverStructuralVariants(PurityPloidyEstimateApplication.java:275)

	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:166)

	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:99)
`

The relevant lines in the recovery VCF that contain the particular ID that PURPLE is not finding are:
`
[jvalleinclan@n0082 MC-H1.2_O]$ gunzip -c OC114-2-organoid-E18-00606-II-O88.gridss.somatic.full.vcf.gz | grep gridss12_25194h

2	133038460	gridss12_25194o	T	[5:71146742[T	16701.63	ihomlen	AS=0;ASQ=0;ASRP=0;ASSR=0;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BQ=64252.36;BSC=2514;BSCQ=51067.72;BUM=514;BUMQ=13184.64;BVF=2034;CAS=0;CASQ=0;CIPOS=-7,6;CQ=16682.85;EVENT=gridss12_25194;HOMLEN=13;HOMSEQ=TTACCGCACTGGA;IC=0;IHOMPOS=-209,-7;IQ=0;PARID=gridss12_25194h;RAS=0;RASQ=0;REF=210;REFPAIR=1551;RP=1057;RPQ=16682.85;SB=1;SC=1X12N1X59M99D173M190D159M;SR=1;SRQ=18.78;SVTYPE=BND;VF=1058;BPI_AF=0.618351841028638,0.959165154264973;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:67.36:2:38.37:1:28.99:3:0:0:0:0:0:115:993:0:0:0:0:0	.:0:0:0:0:0:0:0:0:0:0:64185:2512:51029.3:513:13155.6:2031:0:0:0:16701.6:0:95:558:1057:16682.8:1:18.78:1058

5	71146522	gridss12_25194h	A	[2:133038509[A	16682.85	PASS	AS=0;ASQ=0;ASRP=0;ASSR=0;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BQ=15.06;BSC=1;BSCQ=15.06;BUM=0;BUMQ=0;BVF=1;CAS=0;CASQ=0;CIPOS=-218,218;CQ=16682.85;EVENT=gridss12_25194;IC=0;IMPRECISE;IQ=0;PARID=gridss12_25194o;RAS=0;RASQ=0;REF=62;REFPAIR=33;RP=1057;RPQ=16682.85;SB=1;SC=1X435N1X203M;SR=0;SRQ=0;SVTYPE=BND;VF=1057;BPI_AF=0.959165154264973,0.618351841028638;LOCAL_LINKED_BY=;REMOTE_LINKED_BY=	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:30:20:0:0:0:0:0	.:0:0:0:0:0:0:0:0:0:0:15.06:1:15.06:0:0:1:0:0:0:16682.8:0:32:13:1057:16682.8:0:0:1057
`

So indeed that mateID is outside the range that PURPLE is looking for. Any solution for this?
Thanks.

**Comment by d-cameron** [comment] 2019-11-15 05:47
This looks like an issue with the nominal positions in the input VCF:
```
2 133038460 gridss12_25194o T [5:71146742[T
5 71146522 gridss12_25194h A [2:133038509[A
```
Note that the position listed in the `ALT` field does not match the position of the mate. This is an issue with GRIDSS and I've raised it as https://github.com/PapenfussLab/gridss/issues/278

Workaround: edit your VCF so these positions are consistent at both breakends.

**Comment by jaesvi** [comment] 2019-11-21 13:07
HI Daniel,
Just realized I never replied here. Indeed editing the VCF fixed it. I'll leave the issue open so you can close it when you have a fix at GRIDSS?

Thanks,
Jose

**Comment by DarioS** [comment] 2020-01-29 02:00
But is it O.K. to edit the V.C.F. file by hand if it's cancer patient data for a journal article? Have you thought about how that would sound in the Methods section "We used gedit version 3.30.2 to open each V.C.F. file and changed some numbers to match some other numbers." Not quite reproducible research.

**Comment by p-priestley** [comment] 2020-02-04 04:30
Closing since issue is logged in GRIDSS github  PapenfussLab/gridss#278

**Closed** 2020-02-04 04:30 UTC
